/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Player, Match, Standing, NewsItem, GalleryItem, Convocation, NotificationLog } from './types';

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'p1',
    nombre: 'Guillermina',
    apellido: 'Alvarez Luppo',
    numeroCamiseta: 77,
    posicion: 'Delantera',
    fechaNacimiento: '2013-05-14',
    fotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p2',
    nombre: 'Maria Paz',
    apellido: 'Arroyo Herrero',
    numeroCamiseta: 10,
    posicion: 'Delantera',
    fechaNacimiento: '2013-02-28',
    fotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 4,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma',
    destacada: true
  },
  {
    id: 'p3',
    nombre: 'Candela',
    apellido: 'Barraquero Martinez',
    numeroCamiseta: 12,
    posicion: 'Volante',
    fechaNacimiento: '2013-11-05',
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 4,
    asistencias: 2,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p4',
    nombre: 'Catalina',
    apellido: 'Benito Torciva',
    numeroCamiseta: 16,
    posicion: 'Volante',
    fechaNacimiento: '2013-06-12',
    fotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 1,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p5',
    nombre: 'Brunela',
    apellido: 'Bruschi Lopez',
    numeroCamiseta: 47,
    posicion: 'Defensora',
    fechaNacimiento: '2013-04-03',
    fotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 1,
    tarjetaVerde: 1,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p6',
    nombre: 'Julieta',
    apellido: 'Buscemi Campos',
    numeroCamiseta: 1,
    posicion: 'Arquera',
    fechaNacimiento: '2013-08-19',
    fotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 0,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p7',
    nombre: 'Maria Luz',
    apellido: 'Carrion Hernandez',
    numeroCamiseta: 2,
    posicion: 'Volante',
    fechaNacimiento: '2013-01-22',
    fotoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 11,
    goles: 7,
    asistencias: 2,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p8',
    nombre: 'Carola',
    apellido: 'Guerendian Torcecilla',
    numeroCamiseta: 27,
    posicion: 'Delantera',
    fechaNacimiento: '2013-07-31',
    fotoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p9',
    nombre: 'Lara',
    apellido: 'Kim',
    numeroCamiseta: 67,
    posicion: 'Volante',
    fechaNacimiento: '2013-10-10',
    fotoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 7,
    asistencias: 2,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p10',
    nombre: 'Nagore Ahinara',
    apellido: 'Pardo Astudillo',
    numeroCamiseta: 70,
    posicion: 'Delantera',
    fechaNacimiento: '2013-12-01',
    fotoUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p11',
    nombre: 'Julia',
    apellido: 'Pérez Toledo',
    numeroCamiseta: 0,
    posicion: 'Delantera',
    fechaNacimiento: '2013-09-15',
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 11,
    goles: 0,
    asistencias: 1,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p12',
    nombre: 'Paulina',
    apellido: 'Reynoso',
    numeroCamiseta: 65,
    posicion: 'Defensora',
    fechaNacimiento: '2013-03-22',
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 1,
    asistencias: 0,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p13',
    nombre: 'Ema',
    apellido: 'Riva Perez',
    numeroCamiseta: 25,
    posicion: 'Delantera',
    fechaNacimiento: '2013-08-08',
    fotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 11,
    goles: 5,
    asistencias: 2,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma'
  },
  {
    id: 'p14',
    nombre: 'Delfina',
    apellido: 'Fornetti Chavero',
    numeroCamiseta: 19,
    posicion: 'Defensora',
    fechaNacimiento: '2013-02-14',
    fotoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=200',
    partidosJugados: 12,
    goles: 0,
    asistencias: 0,
    tarjetaVerde: 0,
    tarjetaAmarilla: 0,
    tarjetaRoja: 0,
    categoria: '7ma',
    destacada: true
  }
];

export const INITIAL_MATCH_LIST: Match[] = [
  // --- FECHA 1 ---
  {
    id: 'm1',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Estadio San Jorge',
    golesPropios: 4,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p7',
    goleadorasIds: [{ jugadorId: 'p4', cantidad: 1 }, { jugadorId: 'p7', cantidad: 2 }, { jugadorId: 'p3', cantidad: 1 }],
  },
  {
    id: 'm_f1_g1',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Cancha Tacurú',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g2',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Teqüe B',
    cancha: 'Cancha Maristas',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g3',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Pumai',
    cancha: 'Cancha Maristas',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g_riva',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Alemán B',
    cancha: 'Rivadavia Hockey',
    golesPropios: 12,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g_ltod',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Los Tordos C',
    cancha: 'Los Tordos 1',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g_mendo',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f1_g_bmz_b_cabna',
    fecha: '2026-03-07',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'CABNA',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 2 ---
  {
    id: 'm2',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p7',
    goleadorasIds: [{ jugadorId: 'p2', cantidad: 1 }, { jugadorId: 'p7', cantidad: 1 }, { jugadorId: 'p13', cantidad: 1 }],
  },
  {
    id: 'm_f2_g1',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'San Jorge',
    cancha: 'Estadio Mendoza',
    golesPropios: 4,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g2',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'CABNA',
    visitanteNombre: 'Murialdo B',
    cancha: 'Estadio CABNA',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g_riva',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'Rivadavia',
    cancha: 'Pumai',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g_ltod',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Los Tordos 1',
    golesPropios: 1,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g_ltob',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Alemán B',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Alemán',
    golesPropios: 0,
    golesRival: 5,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g_marb',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Maristas B',
    cancha: 'Tacurú',
    golesPropios: 0,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f2_g_teq_marb_c',
    fecha: '2026-03-14',
    hora: '11:00',
    rival: 'Maristas C',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'Maristas C',
    cancha: 'Sede Teqüe RC',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 3 ---
  {
    id: 'm3',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'San Rafael Tenis Club',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p7',
    goleadorasIds: [{ jugadorId: 'p7', cantidad: 1 }],
    tarjetas: [{ jugadorId: 'mendo_card_f3', verde: 1 }],
  },
  {
    id: 'm_f3_g1',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Cancha Maristas',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f3_g2',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Teqüe B',
    cancha: 'Rivadavia Hockey',
    golesPropios: 11,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f3_g_ltod',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Los Tordos C',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f3_g_ltob',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Pumai',
    cancha: 'Los Tordos 1',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'ltob_card_f3', verde: 1 }]
  },
  {
    id: 'm_f3_g_mar_c_tacu_a',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Tacurú',
    cancha: 'Maristas 2',
    golesPropios: 1,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f3_g_sjor_cabna_a',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'CABNA',
    cancha: 'Sede San Jorge',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f3_g_bmz_b_alem_b',
    fecha: '2026-03-21',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Alemán B',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 1,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 4 ---
  {
    id: 'm4',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'CABNA',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Estadio CABNA',
    golesPropios: 4,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p9',
    goleadorasIds: [{ jugadorId: 'p9', cantidad: 2 }, { jugadorId: 'p7', cantidad: 1 }, { jugadorId: 'p13', cantidad: 1 }],
  },
  {
    id: 'm_f4_g1',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 0,
    golesRival: 3,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g2',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'Alemán B',
    visitanteNombre: 'Murialdo B',
    cancha: 'Cancha Club Alemán',
    golesPropios: 2,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g_riva',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Rivadavia',
    cancha: 'Tacurú',
    golesPropios: 1,
    golesRival: 12,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g_ltod',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'San Jorge',
    cancha: 'Los Tordos 2',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g_ltob',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Teqüe',
    golesPropios: 1,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g_marb',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Maristas C',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Maristas C',
    cancha: 'Maristas 2',
    golesPropios: 2,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f4_g_pumai_bmz_b',
    fecha: '2026-03-28',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Pumai',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 5 ---
  {
    id: 'm5',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Los Tordos C',
    cancha: 'San Rafael Tenis Club',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p13',
    goleadorasIds: [{ jugadorId: 'p13', cantidad: 1 }],
    tarjetas: [{ jugadorId: 'p5', verde: 1 }]
  },
  {
    id: 'm_f5_g1',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Cancha Maristas',
    golesPropios: 0,
    golesRival: 3,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f5_g2',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Maristas B',
    cancha: 'Rivadavia Hockey',
    golesPropios: 9,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'riva_card_f5', verde: 1 }]
  },
  {
    id: 'm_f5_g_ltob',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Tacurú',
    cancha: 'Los Tordos 1',
    golesPropios: 4,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f5_g_mendo',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'CABNA',
    cancha: 'Mendoza R.C.',
    golesPropios: 8,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f5_g_bmz_b_teq',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Teqüe B',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 6,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f5_g_sjor_alem_b',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Alemán',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'Alemán B',
    cancha: 'Sede San Jorge',
    golesPropios: 2,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f5_g_mur_b_pumai_a',
    fecha: '2026-04-11',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Pumai',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 6 ---
  {
    id: 'm6_1',
    fecha: '2026-04-18',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'CABNA',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm6_2',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'Murialdo B',
    cancha: 'Cancha Teqüe RC',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm6',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: false,
    localNombre: 'Alemán B',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Club Alemán de Mendoza',
    golesPropios: 3,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p13',
    goleadorasIds: [{ jugadorId: 'p9', cantidad: 1 }, { jugadorId: 'p13', cantidad: 1 }, { jugadorId: 'p3', cantidad: 1 }],
  },
  {
    id: 'm_f6_g1',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Los Tordos 1',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f6_g_riva',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Maristas C',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Rivadavia',
    cancha: 'Maristas 1',
    golesPropios: 0,
    golesRival: 6,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f6_g_ltob',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Maristas 1',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f6_g_tacu_bco_mza_b',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Tacurú',
    golesPropios: 1,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f6_g_pumai_sjor_a',
    fecha: '2026-05-16',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'San Jorge',
    cancha: 'Pumai',
    golesPropios: 4,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm7',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Pumai',
    cancha: 'Cancha Principal SRTC',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    goleadorasIds: [],
  },
  {
    id: 'm_f7_g1',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Rivadavia Hockey',
    golesPropios: 13,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'rival_card_f7', verde: 1 }]
  },
  {
    id: 'm_f7_g2',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'Teqüe B',
    cancha: 'Estadio San Jorge',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f7_g_ltod',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'CABNA',
    visitanteNombre: 'Los Tordos C',
    cancha: 'CABNA',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f7_g_ltob',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Maristas C',
    cancha: 'Los Tordos 1',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f7_g_mendo',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'Alemán B',
    cancha: 'Mendoza R.C.',
    golesPropios: 7,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f7_g_marb',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Maristas B',
    cancha: 'Banco Mendoza',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f7_g_mur_b_tacu_a',
    fecha: '2026-04-25',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Tacurú',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm8',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Sede Teqüe RC General Ortega',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p9',
    goleadorasIds: [{ jugadorId: 'p9', cantidad: 1 }, { jugadorId: 'p3', cantidad: 1 }],
  },
  {
    id: 'm_f8_g1',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'Los Tordos C',
    cancha: 'Banco Mendoza',
    golesPropios: 0,
    golesRival: 5,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f8_g2',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'Alemán B',
    visitanteNombre: 'CABNA',
    cancha: 'Estadio Club Alemán',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f8_g_riva',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Rivadavia Hockey',
    golesPropios: 7,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'rival_card_f8', verde: 1 }]
  },
  {
    id: 'm_f8_g_mendo',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Pumai',
    golesPropios: 0,
    golesRival: 3,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f8_g_marb',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Murialdo B',
    cancha: 'Maristas 1',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f8_g_tacu_sjor_a',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'San Jorge',
    cancha: 'Tacurú',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f8_g_marc_bmz_b',
    fecha: '2026-05-02',
    hora: '11:00',
    rival: 'Maristas C',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Cancha Maristas',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm9',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Tacurú',
    cancha: 'Cancha Principal SRTC',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p13',
    goleadorasIds: [{ jugadorId: 'p13', cantidad: 1 }, { jugadorId: 'p2', cantidad: 1 }, { jugadorId: 'p12', cantidad: 1 }],
    tarjetas: [{ jugadorId: 'tacu_card_f9', verde: 1 }],
  },
  {
    id: 'm_f9_g1',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Los Tordos 1',
    golesPropios: 2,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f9_g2',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'Teqüe B',
    cancha: 'Estadio Mendoza Hockey',
    golesPropios: 4,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'teq_b_card_f9', amarilla: 1 }]
  },
  {
    id: 'm_f9_g_riva',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Rivadavia',
    cancha: 'Banco Mendoza',
    golesPropios: 0,
    golesRival: 6,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f9_g_ltod',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Alemán B',
    cancha: 'Los Tordos 2',
    golesPropios: 6,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f9_g_marb',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'Maristas B',
    cancha: 'Sede San Jorge',
    golesPropios: 0,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f9_g_cabna_pumai_a',
    fecha: '2026-05-09',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: false,
    localNombre: 'CABNA',
    visitanteNombre: 'Pumai',
    cancha: 'Cancha CABNA',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 10 ---
  {
    id: 'm10',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Cancha Maristas Rugby Club',
    golesPropios: 2,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p2',
    goleadorasIds: [{ jugadorId: 'p2', cantidad: 1 }, { jugadorId: 'p3', cantidad: 1 }],
  },
  {
    id: 'm_f10_g1',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'Alemán B',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 3,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g2',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Club Tacurú',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g_riva',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'Murialdo B',
    cancha: 'Rivadavia Hockey',
    golesPropios: 9,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g_ltod',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'Los Tordos C',
    cancha: 'Pumai',
    golesPropios: 0,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g_ltob',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Los Tordos 1',
    golesPropios: 2,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g_teq_cabna',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'CABNA',
    cancha: 'Sede Teqüe RC',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f10_g_mar_c_sjor_a',
    fecha: '2026-05-23',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'San Jorge',
    cancha: 'Maristas 1',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 15 ---
  {
    id: 'm15',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Murialdo B',
    cancha: 'Cancha Principal SRTC',
    golesPropios: 4,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p9',
    goleadorasIds: [{ jugadorId: 'p9', cantidad: 2 }, { jugadorId: 'p7', cantidad: 2 }],
  },
  {
    id: 'm_f15_g1',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Sede San Jorge',
    golesPropios: 1,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'bmzc_card_f15_sjor', verde: 1 }]
  },
  {
    id: 'm_f15_g_riva',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Rivadavia',
    cancha: 'Los Tordos 1',
    golesPropios: 0,
    golesRival: 4,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f15_g_ltob',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'CABNA',
    visitanteNombre: 'Los Tordos B',
    cancha: 'CABNA',
    golesPropios: 0,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'ltob_card_f15', verde: 1 }]
  },
  {
    id: 'm_f15_g_mendo',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: false,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f15_g_marb',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Maristas B',
    esLocal: false,
    localNombre: 'Pumai',
    visitanteNombre: 'Maristas B',
    cancha: 'Pumai',
    golesPropios: 1,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f15_g_teq_tacuru',
    fecha: '2026-05-25',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: false,
    localNombre: 'Teqüe B',
    visitanteNombre: 'Tacurú',
    cancha: 'Sede Teqüe RC',
    golesPropios: 0,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
  },

  // --- FECHA 14 ---
  {
    id: 'm14',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: false,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 2,
    golesRival: 2,
    estado: 'Finalizado',
    categoria: '7ma',
    mvpId: 'p9',
    goleadorasIds: [{ jugadorId: 'p9', cantidad: 1 }, { jugadorId: 'p2', cantidad: 1 }],
  },
  {
    id: 'm_f14_g1',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Teqüe B',
    esLocal: false,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'Teqüe B',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [
      { jugadorId: 'bmzc_card_f14', verde: 2 },
      { jugadorId: 'teq_b_card_f14', verde: 1 }
    ]
  },
  {
    id: 'm_f14_g_riva',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'CABNA',
    cancha: 'Rivadavia Hockey',
    golesPropios: 10,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f14_g_ltod',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Los Tordos C',
    esLocal: false,
    localNombre: 'Maristas C',
    visitanteNombre: 'Los Tordos C',
    cancha: 'Marista 2',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'rival_card_f14', verde: 1 }]
  },
  {
    id: 'm_f14_g_ltob',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Los Tordos B',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Los Tordos 1',
    golesPropios: 3,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f14_g_marb',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: false,
    localNombre: 'Maristas B',
    visitanteNombre: 'Alemán B',
    cancha: 'Maristas 1',
    golesPropios: 5,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  {
    id: 'm_f14_g_tacu_pumai_a',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: false,
    localNombre: 'Tacurú',
    visitanteNombre: 'Pumai',
    cancha: 'Tacurú',
    golesPropios: 2,
    golesRival: 1,
    estado: 'Finalizado',
    categoria: '7ma',
    tarjetas: [{ jugadorId: 'pumai_card_f14_tacu', amarilla: 1 }]
  },
  {
    id: 'm_f14_g_mur_b_sjor_a',
    fecha: '2026-05-30',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'San Jorge',
    cancha: 'Murialdo',
    golesPropios: 1,
    golesRival: 0,
    estado: 'Finalizado',
    categoria: '7ma',
  },
  // --- FECHA 11 (20-Jun-2026) ---
  {
    id: 'm_f11_g1',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: true,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g2',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: false,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g3',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Rivadavia',
    esLocal: false,
    localNombre: 'San Jorge',
    visitanteNombre: 'Rivadavia',
    cancha: 'Sede San Jorge',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm11',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Marista C',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Marista C',
    cancha: 'Cancha Principal SRTC',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g4',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Marista B',
    esLocal: true,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'Marista B',
    cancha: 'Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g5',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: true,
    localNombre: 'CABNA',
    visitanteNombre: 'Tacurú',
    cancha: 'CABNA',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g6',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Teqüe Rugby Club',
    esLocal: false,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Teqüe Rugby Club',
    cancha: 'Los Tordos 1',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f11_g7',
    fecha: '2026-06-20',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: true,
    localNombre: 'Alemán B',
    visitanteNombre: 'Pumai',
    cancha: 'Club Alemán',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },

  // --- FECHA 12 (06-Jun-2026) ---
  {
    id: 'm_f12_g1',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Pumai',
    esLocal: true,
    localNombre: 'Banco Mendoza C',
    visitanteNombre: 'Pumai',
    cancha: 'Banco Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g2',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Alemán B',
    esLocal: true,
    localNombre: 'Teqüe Rugby Club',
    visitanteNombre: 'Alemán B',
    cancha: 'Sede Teqüe RC',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g3',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: true,
    localNombre: 'Tacurú',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Club Tacurú',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g4',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'CABNA',
    esLocal: true,
    localNombre: 'Marista B',
    visitanteNombre: 'CABNA',
    cancha: 'Maristas 1',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g5',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Mendoza R.C.',
    esLocal: true,
    localNombre: 'Marista C',
    visitanteNombre: 'Mendoza R.C.',
    cancha: 'Maristas 2',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm12',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Rivadavia',
    esLocal: false,
    localNombre: 'Rivadavia',
    visitanteNombre: 'San Rafael Tenis Club',
    cancha: 'Estadio Rivadavia Hockey',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g6',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'San Jorge',
    esLocal: true,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'San Jorge',
    cancha: 'Los Tordos 1',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f12_g7',
    fecha: '2026-06-06',
    hora: '11:00',
    rival: 'Murialdo B',
    esLocal: true,
    localNombre: 'Banco Mendoza B',
    visitanteNombre: 'Murialdo B',
    cancha: 'Estadio Banco Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },

  // --- FECHA 13 (13-Jun-2026) ---
  {
    id: 'm_f13_g1',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Banco Mendoza C',
    esLocal: true,
    localNombre: 'Murialdo B',
    visitanteNombre: 'Banco Mendoza C',
    cancha: 'Murialdo',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g2',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Banco Mendoza B',
    esLocal: true,
    localNombre: 'San Jorge',
    visitanteNombre: 'Banco Mendoza B',
    cancha: 'Sede San Jorge',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm13',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Los Tordos B',
    esLocal: true,
    localNombre: 'San Rafael Tenis Club',
    visitanteNombre: 'Los Tordos B',
    cancha: 'Cancha Principal SRTC',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g3',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Rivadavia',
    esLocal: true,
    localNombre: 'Mendoza R.C.',
    visitanteNombre: 'Rivadavia',
    cancha: 'Mendoza',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g4',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Marista C',
    esLocal: true,
    localNombre: 'CABNA',
    visitanteNombre: 'Marista C',
    cancha: 'CABNA',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g5',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Marista B',
    esLocal: true,
    localNombre: 'Los Tordos C',
    visitanteNombre: 'Marista B',
    cancha: 'Los Tordos 1',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g6',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Tacurú',
    esLocal: true,
    localNombre: 'Alemán B',
    visitanteNombre: 'Tacurú',
    cancha: 'Club Alemán',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  {
    id: 'm_f13_g7',
    fecha: '2026-06-13',
    hora: '11:00',
    rival: 'Teqüe Rugby Club',
    esLocal: true,
    localNombre: 'Pumai',
    visitanteNombre: 'Teqüe Rugby Club',
    cancha: 'Pumai',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
  },
  // --- COOKED PLAYOFF MATCHES (CUARTOS) ---
  {
    id: 'match_cuartos_1',
    fecha: '2026-06-27',
    hora: '11:00',
    rival: '8vo CLASIFICADO',
    esLocal: true,
    localNombre: '1er CLASIFICADO',
    visitanteNombre: '8vo CLASIFICADO',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'cuartos',
    fechaNumero: 1
  },
  {
    id: 'match_cuartos_2',
    fecha: '2026-06-27',
    hora: '13:00',
    rival: '7mo CLASIFICADO',
    esLocal: true,
    localNombre: '2do CLASIFICADO',
    visitanteNombre: '7mo CLASIFICADO',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'cuartos',
    fechaNumero: 1
  },
  {
    id: 'match_cuartos_3',
    fecha: '2026-06-27',
    hora: '15:00',
    rival: '6to CLASIFICADO',
    esLocal: true,
    localNombre: '3er CLASIFICADO',
    visitanteNombre: '6to CLASIFICADO',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'cuartos',
    fechaNumero: 1
  },
  {
    id: 'match_cuartos_4',
    fecha: '2026-06-27',
    hora: '17:00',
    rival: '5to CLASIFICADO',
    esLocal: true,
    localNombre: '4to CLASIFICADO',
    visitanteNombre: '5to CLASIFICADO',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'cuartos',
    fechaNumero: 1
  },
  // --- COOKED PLAYOFF MATCHES (SEMIFINAL) ---
  {
    id: 'match_semi_1',
    fecha: '2026-07-04',
    hora: '12:00',
    rival: 'GANADOR 2',
    esLocal: true,
    localNombre: 'GANADOR 1',
    visitanteNombre: 'GANADOR 2',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'semifinal',
    fechaNumero: 1
  },
  {
    id: 'match_semi_2',
    fecha: '2026-07-04',
    hora: '14:30',
    rival: 'GANADOR 4',
    esLocal: true,
    localNombre: 'GANADOR 3',
    visitanteNombre: 'GANADOR 4',
    cancha: 'Cancha Neutral (A Confirmar)',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'semifinal',
    fechaNumero: 1
  },
  // --- COOKED PLAYOFF MATCHES (FINAL) ---
  {
    id: 'match_final_1',
    fecha: '2026-07-05',
    hora: '15:00',
    rival: 'GANADOR SEMI 2',
    esLocal: true,
    localNombre: 'GANADOR SEMI 1',
    visitanteNombre: 'GANADOR SEMI 2',
    cancha: 'Estadio Ciudad de Godoy Cruz',
    golesPropios: 0,
    golesRival: 0,
    estado: 'Programado',
    categoria: '7ma',
    fase: 'final',
    fechaNumero: 1
  }
];

export const INITIAL_STANDINGS: Standing[] = [
  { id: 'riva_a', equipo: 'RIVADAVIA - A', pj: 12, pg: 12, pe: 0, pp: 0, gf: 103, gc: 1, dg: 102, pts: 36, categoria: '7ma' },
  { id: 'srtc', equipo: 'SAN RAFAEL TENIS CLUB - A', pj: 12, pg: 8, pe: 4, pp: 0, gf: 29, gc: 7, dg: 22, pts: 28, categoria: '7ma', esOficialClub: true },
  { id: 'ltod_c', equipo: 'LOS TORDOS - C', pj: 12, pg: 8, pe: 3, pp: 1, gf: 26, gc: 6, dg: 20, pts: 27, categoria: '7ma' },
  { id: 'ltod_b', equipo: 'LOS TORDOS - B', pj: 12, pg: 8, pe: 2, pp: 2, gf: 28, gc: 11, dg: 17, pts: 26, categoria: '7ma' },
  { id: 'mndz_a', equipo: 'MENDOZA R. C. - A', pj: 12, pg: 7, pe: 4, pp: 1, gf: 36, gc: 8, dg: 28, pts: 25, categoria: '7ma' },
  { id: 'mar_b', equipo: 'MARISTA - B', pj: 12, pg: 7, pe: 2, pp: 3, gf: 21, gc: 15, dg: 6, pts: 23, categoria: '7ma' },
  { id: 'tacu_a', equipo: 'TACURU - A', pj: 12, pg: 7, pe: 1, pp: 4, gf: 18, gc: 24, dg: -6, pts: 22, categoria: '7ma' },
  { id: 'bmzb_b', equipo: 'BANCO MENDOZA - B', pj: 12, pg: 5, pe: 4, pp: 3, gf: 16, gc: 12, dg: 4, pts: 19, categoria: '7ma' },
  { id: 'mar_c', equipo: 'MARISTA - C', pj: 12, pg: 4, pe: 2, pp: 6, gf: 8, gc: 19, dg: -11, pts: 14, categoria: '7ma' },
  { id: 'pumai_a', equipo: 'PUMAI RUGBY CLUB - A', pj: 12, pg: 3, pe: 4, pp: 5, gf: 11, gc: 15, dg: -4, pts: 13, categoria: '7ma' },
  { id: 'sjor_a', equipo: 'SAN JORGE S.R. - A', pj: 12, pg: 2, pe: 3, pp: 7, gf: 6, gc: 23, dg: -17, pts: 9, categoria: '7ma' },
  { id: 'cabn_a', equipo: 'CABNA - A', pj: 12, pg: 2, pe: 3, pp: 7, gf: 5, gc: 32, dg: -27, pts: 9, categoria: '7ma' },
  { id: 'mur_b', equipo: 'MURIALDO - B', pj: 12, pg: 2, pe: 2, pp: 8, gf: 2, gc: 27, dg: -25, pts: 8, categoria: '7ma' },
  { id: 'alem_b', equipo: 'ALEMAN - B', pj: 12, pg: 2, pe: 0, pp: 10, gf: 5, gc: 43, dg: -38, pts: 6, categoria: '7ma' },
  { id: 'teq_b', equipo: 'TEQÜE RUGBY CLUB - B', pj: 12, pg: 0, pe: 3, pp: 9, gf: 1, gc: 33, dg: -32, pts: 3, categoria: '7ma' },
  { id: 'bmzc_c', equipo: 'BANCO MENDOZA - C', pj: 12, pg: 0, pe: 1, pp: 11, gf: 1, gc: 40, dg: -39, pts: 1, categoria: '7ma' }
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'n1',
    titulo: '¡Clásico del Sur con garra de 7ma!',
    contenido: 'La Séptima división venció en una demostración absoluta de carácter a Maristas RC por 2 a 1 en el sintético de nuestra sede principal. Con goles de Martina González y Delfina Rodríguez, el equipo de San Rafael Tenis Club se afianza de forma invicta en lo más alto del torneo. El plantel agradece el incansable aliento de la hinchada, padres y compañeras de otras divisiones.',
    imagenUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    fecha: '2026-05-03',
    autor: 'Comisión de Hockey'
  },
  {
    id: 'n2',
    titulo: 'Convocatoria Oficial vs Los Tordos',
    contenido: 'El cuerpo técnico encabezado por el entrenador principal ha publicado la plantilla de convocadas para disputar el trascendental choque del próximo sábado contra Los Tordos. El bus saldrá desde el club a las 11:30 Hs. Se solicita puntualidad absoluta y llevar indumentaria titular y alternativa roja/azul.',
    imagenUrl: 'https://images.unsplash.com/photo-1510566336338-701a5fb7a126?auto=format&fit=crop&q=80&w=800',
    fecha: '2026-06-01',
    autor: 'Cuerpo Técnico',
    esConvocatoria: true
  },
  {
    id: 'n3',
    titulo: 'Obras en el sintético: Nuevos vestuarios locales',
    contenido: 'Continuando con el plan de mejoras de infraestructura, Club San Rafael Tenis Club ha inaugurado la ampliación de los vestuarios de hockey. Estas nuevas instalaciones cuentan con cabinas individuales para jugadoras, duchas térmicas de alta eficiencia y sala de kinesiología para la recuperación post-partidos.',
    imagenUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&q=80&w=800',
    fecha: '2026-05-25',
    autor: 'CD San Rafael Tenis Club'
  }
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'g1',
    titulo: 'Festejo del Clásico de 7ma',
    imagenUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=600',
    fecha: '2026-05-02',
    partidoRelacionado: 'm1',
    torneo: 'Apertura de la Asociación'
  },
  {
    id: 'g2',
    titulo: 'Abrazo de gol vs Amancay',
    imagenUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&q=80&w=600',
    fecha: '2026-05-16',
    partidoRelacionado: 'm3',
    torneo: 'Apertura de la Asociación'
  },
  {
    id: 'g3',
    titulo: 'Entrenamiento táctico bloque defensivo',
    imagenUrl: 'https://images.unsplash.com/photo-1543326137-f3642b957686?auto=format&fit=crop&q=80&w=600',
    fecha: '2026-05-20',
    torneo: 'Entrenamientos SRTC'
  }
];

export const INITIAL_CONVOCATIONS: Convocation[] = [
  {
    id: 'm6', // matches "m6" vs Los Tordos
    fecha: '2026-06-06',
    rival: 'Los Tordos',
    categoria: '7ma',
    estadosJugadoras: {
      'p1': 'Convocada',
      'p2': 'Convocada',
      'p3': 'Convocada',
      'p4': 'Convocada',
      'p5': 'Convocada',
      'p6': 'Convocada',
      'p7': 'Ausente', // excusada
      'p8': 'Convocada',
      'p9': 'Convocada',
      'p10': 'Lesionada' // con molestia en el tobillo
    }
  }
];

export const INITIAL_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'not1',
    titulo: '¡Salió la convocatoria!',
    cuerpo: 'El entrenador publicó la convocatoria para el encuentro clásico frente a Los Tordos.',
    fecha: '2026-06-01 19:15 Hs',
    tipo: 'convocatoria'
  },
  {
    id: 'not2',
    titulo: 'Fin del partido',
    cuerpo: '7ma División: San Rafael Tenis Club 2 - 2 Banco Mendoza. ¡Empate vibrante de locales!',
    fecha: '2026-05-30 17:35 Hs',
    tipo: 'resultado'
  },
  {
    id: 'not3',
    titulo: 'Nuevo Horario Confirmado',
    cuerpo: 'El partido de la 7ma división vs Amancay Club se reprogramó para las 15:00 Hs del Sábado.',
    fecha: '2026-05-14 11:00 Hs',
    tipo: 'horario'
  }
];

// Historical Seasons for Premium Feature
export const HISTORICAL_SEASONS = [
  { año: 2025, division: '8va División', posicion: 'Campeonas Invictas', puntos: 36, partidos: 14 },
  { año: 2024, division: '9na División', posicion: 'Subcampeonas', puntos: 31, partidos: 12 },
  { año: 2023, division: 'Pre-Décima', posicion: 'Participación Formativa', puntos: 0, partidos: 10 }
];
